DROP DATABASE IF EXISTS 5to_BookFlix;
CREATE DATABASE 5to_BookFlix;
USE 5to_BookFlix;

CREATE TABLE Libro (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Titulo VARCHAR(150) NOT NULL,
    Autor VARCHAR(150) NOT NULL,
    Anio INT,
    Descripcion TEXT,
    Precio DECIMAL(10,2),
    Imagen VARCHAR(255),
    Categoria VARCHAR(100)
);

CREATE TABLE Usuario (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100),
    Apellido VARCHAR(100),
    Correo VARCHAR(150) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL
);
